### ISSUE TITLE
input组件的样式缺失

### ISSUE THREAD

**Issue by huskylengcb** [growingio/gio-design#1547]
**Describe the bug**
input组件样式缺失

**Comment by nnmax** [comment]
> **Describe the bug** input组件样式缺失

版本是多少？旧 Input 还是 新 Input 的

**Comment by huskylengcb** [comment]
> > **Describe the bug** input组件样式缺失
> 
> 版本是多少？旧 Input 还是 新 Input 的

新版Input，master最新分支以及22.2.0版本

commit 号：7cdd93a758eea263e0be75122079969d3f61129f
