### ISSUE TITLE
Select组件 有value值的disabled状态，还是能点击打开下拉框，但是不能选择其他项

### ISSUE THREAD

**Issue by huskylengcb** [growingio/gio-design#1555]
![屏幕快照 2021-11-30 13 56 17](https://user-images.githubusercontent.com/28557953/143993647-0d8cd757-c566-40c2-a65a-83005cecd3df.png)

**Comment by huskylengcb** [comment]
点击那个下拉剪头位置

**Comment by berber1016** [comment]
该问题在22.2.1版本修复了
