### ISSUE TITLE
modal组件footer占位问题以及考录false、null参数的问题

### ISSUE THREAD

**Issue by huskylengcb** [growingio/gio-design#156]
modal组件，footer设置为false或者null时，footer还是存在的，建议处理一下这两种情况 设置一个空的元素时，存在padding值，也会导致footer存在占位的情况

**Comment by phyzess** [comment]
> modal组件，footer设置为false或者null时，footer还是存在的，建议处理一下这两种情况 设置一个空的元素时，存在padding值，也会导致footer存在占位的情况

设置为false 和 null 还存在 footer 的情况我没看到，目前只有在未设置 `onOk` 且 `dropCloseButton=true` 时，才不会有 Footer，你遇到的是什么情况下的？
footer 传空元素的情况我个人觉得不是组件需要进行判断的，是使用者需要确认的吧？否则组件需要拿 footer 的 React 元素来判断 children？
