### ISSUE TITLE
【List】 组件 ，disabled是假的，hover、click事件都能触发，disable后，hover还有hover的颜色

### ISSUE THREAD

**Issue by huskylengcb** [growingio/gio-design#1563]

**Comment by berber1016** [comment]
补充：在dropdown下使用List组件 点击 disabled状态的 item 导致 关闭dropdown

**Comment by berber1016** [comment]
dropdown 下 如果是非受控模式，点什么都会绑定onClick方法 关闭 dropdown 建议采取受控模式

**Comment by berber1016** [comment]
该 PR 中 新增了 受控模式的 demo 
https://github.com/growingio/gio-design/pull/1569
