### ISSUE TITLE
radio 组件，onchange方法响应有问题，切换时，有时不触发onchange事件

### ISSUE THREAD

**Issue by huskylengcb** [growingio/gio-design#160]
radio 组件，onchange方法响应有问题，切换时，有时不触发onchange事件

**Comment by phyzess** [comment]
> radio 组件，onchange方法响应有问题，切换时，有时不触发onchange事件

是在用 RadioGroup 的时候还是单独用 Radio 的时候？

**Comment by huskylengcb** [comment]
> > radio 组件，onchange方法响应有问题，切换时，有时不触发onchange事件
> 
> 是在用 RadioGroup 的时候还是单独用 Radio 的时候？

Radio Group的时候
