### ISSUE TITLE
【modal】组件，footer为false或者null时，有一个“取消按钮”

### ISSUE THREAD

**Issue by huskylengcb** [growingio/gio-design#1639]
![屏幕快照 2021-12-07 20 26 32](https://user-images.githubusercontent.com/28557953/145028724-4967860e-c6d4-4640-9ef9-c668f80ca6ec.png)

![屏幕快照 2021-12-07 20 27 39](https://user-images.githubusercontent.com/28557953/145028886-60209a10-6485-43a6-aacf-872145cf8e9d.png)

两层footer

**Comment by WORLDI** [comment]
看了下是footer的判断逻辑有问题，把 || 换成 ?? 并且把判断放在div外面是不是更合适点

**Comment by berber1016** [comment]
已于 该PR修复 https://github.com/growingio/gio-design/pull/1642
