### ISSUE TITLE
[PastTimePicker]: 选择固定日期时点击月份，选中月份无法弹出日期选择

### ISSUE THREAD

**Issue by hiker90** [growingio/gio-design#1984]
**Describe the bug**
选择固定日期时点击月份，选中月份无法弹出日期选择

**To Reproduce**
1. 触发事件选择器
2. 选择固定日期
3. 点击月份
4. 选择月份

**Expected behavior**
选择月份后应弹出日期选择

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by gavin-hao** [comment]
fixed   ---22/4/26
