### ISSUE TITLE
[StepModal] support interrupt next step

### ISSUE THREAD

**Issue by LEEHONCN** [growingio/gio-design#244]
**Is your feature request related to a problem? Please describe.**
跳转下一步可以根据 ajax 请求返回值来确定是否进入下一步。如移交负责人操作需要先验证密码，通过验证才能进入下一步。

**Describe the solution you'd like**
根据现在的代码逻辑，暂时没有想法。

**Comment by phyzess** [comment]
![image](https://user-images.githubusercontent.com/25143884/93839011-2bf9d300-fcbe-11ea-9434-3fd4a9c6983b.png)
在onNext里面返回一个 Promise 试试

**Comment by LEEHONCN** [comment]
> ![image](https://user-images.githubusercontent.com/25143884/93839011-2bf9d300-fcbe-11ea-9434-3fd4a9c6983b.png)
> 在onNext里面返回一个 Promise 试试

返回 Promise 没有中断下一步啊。后两个语句也应该放到Promise里吧？
