### ISSUE TITLE
[List] 应该有 padding 值

### ISSUE THREAD

**Issue by LEEHONCN** [growingio/gio-design#260]
**Describe the bug**
应该有 padding 值

**Screenshots**
![截屏2020-09-25 上午11 05 56](https://user-images.githubusercontent.com/29272287/94222126-1f27ea00-ff1f-11ea-88ee-e4b4c0dae996.png)

**Comment by jack0pan** [comment]
@LEEHONCN 你的意思是现在没有 padding？

**Comment by LEEHONCN** [comment]
现在的 padding 是demo里写的
