### ISSUE TITLE
 Select 组件样式 token 丢失

### ISSUE THREAD

**Issue by phyzess** [growingio/gio-design#264]
**Describe the bug**
Select 组件时样式报错

**To Reproduce**
1. 按需引入 Select 组件
2. 编译未通过
![image](https://user-images.githubusercontent.com/25143884/94334909-5cb57180-000a-11eb-8101-585688cef4d2.png)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: chrome

**Additional context**

**Comment by phyzess** [comment]
在 PopConfirm 组件里也看到了类似情况，token 丢失，是不是之前我那次发版的时候token和 icons 没发成功也有关？
需要重新再发一次token 和 icons

**Comment by jack0pan** [comment]
@phyzess 确实发包的问题

**Comment by phyzess** [comment]
后续还是有一些问题，从文档上我看不到 Select 组件的正确使用方法，包括 value 传入现在是报错的，提示接口不支持 value 这个 prop @jack0pan

**Comment by jack0pan** [comment]
> 后续还是有一些问题，从文档上我看不到 Select 组件的正确使用方法，包括 value 传入现在是报错的，提示接口不支持 value 这个 prop @jack0pan

初始化时候设置默认值？
