### ISSUE TITLE
[Input] Input 问题汇总

### ISSUE THREAD

**Issue by iahu** [growingio/gio-design#269]
**Describe the bug**
`Input` value 默认为 `undefined`，然后更新 value 为 '123' 之类的值后控制台会有 warning

**To Reproduce**
[复现链接](https://codesandbox.io/s/mutable-wave-2f6yh?file=/demo.tsx)

**Expected behavior**
任何时候都为受控组件

**Comment by LEEHONCN** [comment]
input 不应该设定宽度

**Comment by LEEHONCN** [comment]
value 字段应该可以受控也可以不受控

**Comment by iahu** [comment]
Input 默认宽度被写死，并且与旧的 @gio-design 的 className 重名，导致很多意外情况。

**Comment by LEEHONCN** [comment]
不要使用两种 style 参数。SearchBar 有三种 style 参数

**Comment by LEEHONCN** [comment]
input 的表现应该是 行内元素

**Comment by zzt1224** [comment]
input有个 gio-input 的外层样式， 没有对外api， 大家都在覆盖这个样式 引起很多冲突

**Comment by phyzess** [comment]
> 不要使用两种 style 参数。这样也导致了 SearchBar 有三种 style 参数

+1, wrapStyle和 inputStyle 的设计造成了很多替换时候的麻烦

**Comment by phyzess** [comment]
- API 文档写的不是很全，用了省略号，很疑惑

- 缺少 `addonBefore` 这样的 API，导致与原先的无法兼容
