### ISSUE TITLE
[Select] Select组件无法使用value进行传值

### ISSUE THREAD

**Issue by phyzess** [growingio/gio-design#278]
**Describe the bug**
组件无法使用 value prop 进行传值，不太符合一般使用习惯

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by LEEHONCN** [comment]
需要符合 Form 的约定，使用 value 字段。
