### ISSUE TITLE
修复 StyleLint 和 ESLint 错误

### ISSUE THREAD

**Issue by jack0pan** [growingio/gio-design#297]
按照以下流程修复：
1. 从后文中有问题的组件列表中选择一个，在组件名后面加上自己的 ID，表示自己在修复，防止其他人重复修复。
2. 为自己的开发工具安装 stylelint 和 eslint 插件，根据提示修复问题。
3. 修复完后，提交 PR，等 PR 被 Merged 后，在后面列表中勾掉，表示组件修复完毕。

目前已知有问题的组件：

- [x] date-picker@WORLDI
- [x] form  @iahu 
- [x] list@WORLDI
- [x] loading@WORLDI
- [x] menu @phyzess 
- [x] modal @phyzess 
- [x] pagination@WORLDI
- [x] popconfim@WORLDI
- [x] popover@WORLDI
- [x] progress [#353]
- [x] radio @phyzess 
- [x] searchBar@WORLDI
- [x] sign @phyzess 
- [x] skeleton@WORLDI
- [x] table@WORLDI
- [x] tabNav@WORLDI
- [x] tabs@WORLDI
- [x] tag [#357]
- [x] timePicker@WORLDI
- [x] toast@WORLDI
- [x] toggles@WORLDI
- [x] tooltip@WORLDI
- [x] upload @phyzess #352

**Comment by phyzess** [comment]
warn 级别的需要修改么 @jack0pan

**Comment by jack0pan** [comment]
@phyzess 把 error 修了就行了
