### ISSUE TITLE
希望增加一些组件

### ISSUE THREAD

**Issue by iahu** [growingio/gio-design#305]
对比旧版，发现新版有一些组件未被实现，希望以下组件可以在新版得到实现

- [x] Ellipsis
- [x] Gap
- [x] Icons
  - copy
  - close
  - sequence
  - info
  - download
  - exclamation
- ~~[ ] Modal 组件，缺少disableOk这个方法~~ 通过 okButtonProps中传入 disable 实现

**Comment by phyzess** [comment]
@iahu 关于 Radio.Item，是希望实现像antd 那样 Radio.Button 的效果？还是能够自己传入一个component或者是 render 来进行每一个 radio 的渲染？

**Comment by itiiss** [comment]
> @iahu 关于 Radio.Item，是希望实现像antd 那样 Radio.Button 的效果？还是能够自己传入一个component或者是 render 来进行每一个 radio 的渲染？

希望是像antd那样button的效果

**Comment by phyzess** [comment]
> * [ ] Modal 组件，缺少disableOk这个方法

通过 okButtonProps中传入 disable 实现
