### ISSUE TITLE
[Table] ellipsis属性为true时，render内容为空

### ISSUE THREAD

**Issue by huskylengcb** [growingio/gio-design#313]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by zzt1224** [comment]
标注一下是什么组件

**Comment by LEEHONCN** [comment]
rc-table 的 ellipsis 只是提供了一个样式。我内部使用render方法来实现超出显示Tooltip。目前修改后的逻辑是 当 条件 has(column, 'ellipsis') && has(column, 'width') && !has(column, 'render') 满足时，使用内部赋值 render方法来显示tooltip
