### ISSUE TITLE
[Popover] hover 的触发逻辑在某种情况下相反了

### ISSUE THREAD

**Issue by itiiss** [growingio/gio-design#316]
**Describe the bug**
鼠标移入的时候popover消失，移出的时候反而出现
使用代码如下

`              <Popover
                prefixCls={ 'funnel-poptip ant-popover' }
                trigger='hover'
                contentArea={ <div>{ I18n.t('funnels.total_conversion_rate') }</div> }
              >
                <span className='thead'>
                  { I18n.t('funnels.total_conversion_rate') }
                </span>
              </Popover>`

**Comment by LEEHONCN** [comment]
需要多一些的信息 @itiiss

**Comment by jack0pan** [comment]
应该是使用问题。
