### ISSUE TITLE
Tooltip  组件是否可提供disable prop

### ISSUE THREAD

**Issue by phyzess** [growingio/gio-design#332]
**Is your feature request related to a problem? Please describe.**
 多处场景需要根据某条数据数量等判断条件，决定是否显示 tooltip

**Describe the solution you'd like**
Tooltip 是否可以提供一个 disabled prop 用于外部控制是否起效

**Describe alternatives you've considered**

**Additional context**

**Comment by phyzess** [comment]
@jack0pan 但是 Tooltip 的使用是需要把其他组件放在 Tooltip 内部的,内部的组件需要一直显示,比如：某个条件下禁用的 Button，同时 hover 显示提示文字；但 Button 没有被禁用时不需要 tooltip 的文字

**Comment by iahu** [comment]
内部只要判断disabled就可以直接返回children，外部判断相对麻烦。
