### ISSUE TITLE
[Modal]期望提供一个beforeClose钩子函数

### ISSUE THREAD

**Issue by itiiss** [growingio/gio-design#343]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by phyzess** [comment]
这里的 beforeClose 是指在执行 onClose 之前么？

**Comment by itiiss** [comment]
> @itiiss 这里的 beforeClose 是指在执行 onClose 之前么？需要这个钩子的目的与大致场景可以说一下么？

旧版的design有一个disableOK的函数作为参数，可以做一些校验modal里面的操作，然后阻止modal的关闭。
抽象成更通用的beforeClose，可以做一些校验和其他的操作
