### ISSUE TITLE
[SearchBar] storage 展示面板宽度问题

### ISSUE THREAD

**Issue by phyzess** [growingio/gio-design#400]
**Describe the bug**
![image](https://user-images.githubusercontent.com/25143884/97960230-00552700-1dec-11eb-9079-00d7ddc0f643.png)
如图如果 SearchBar 在边上，storage 的展示面板会超出屏幕且没有进行自适应。
可否给一个 props 类似于 tooltip 的 placement，或者让展示面板适应 searchbar 的宽度？

**Comment by WORLDI** [comment]
https://github.com/growingio/gio-design/pull/408
