### ISSUE TITLE
[Input] Input 组件可否提供状态 props

### ISSUE THREAD

**Issue by phyzess** [growingio/gio-design#404]
Input 组件可否提供类似于 error, success, warn 这样的 props，用于改变 input 的边框颜色？

**Comment by jack0pan** [comment]
这个应该在 Form 那里提供。

**Comment by phyzess** [comment]
> 这个应该在 Form 那里提供。

很多时候不会在 Input 外面套一层 Form而是直接使用 Input，这个自己在业务中进行封装么？
