### ISSUE TITLE
[components]Token使用px单位替换rem单位

### ISSUE THREAD

**Issue by itiiss** [growingio/gio-design#405]
现在的token全部使用的是rem单位，在一些组件中，size的参数也是用rem作为单位。因为我们没有做移动端的适配，是否可以考虑按照1rem = 16 px 换成px单位。

**Comment by LEEHONCN** [comment]
@jack0pan 之前说不是改组件的单位，而是改项目HTML节点的 fontsize

**Comment by LEEHONCN** [comment]
这个可以关了吗 @itiiss  @jack0pan

**Comment by LEEHONCN** [comment]
https://github.com/growingio/gio-design/pull/515
https://github.com/growingio/gio-design/pull/525
