### ISSUE TITLE
[Avatar] AvatarGroup users 可否提供更多选项

### ISSUE THREAD

**Issue by phyzess** [growingio/gio-design#418]
![image](https://user-images.githubusercontent.com/25143884/98195362-885a3e80-1f5c-11eb-933c-2760dc112ff6.png)

- 当前应用场景有这样的情况，hover 时显示额外提示 tips，当前AvatarGroup 中的 users 无法支持

- 另外如上图，如果将 avatar 放置在 table 中，hover 时背景色的统一会让 avatar 比较难以辨别，可否考虑添加 hover 时的边框或者 box-shadow？图中的示例单独使用了 Avatar，没有用 AvatarGroup

**Comment by jack0pan** [comment]
@phyzess 这个我先让设计师解决颜色冲突问题。
