### ISSUE TITLE
[Button] Button 组件颜色问题

### ISSUE THREAD

**Issue by phyzess** [growingio/gio-design#423]
- Button 为 `ghost` 类型的时候，其内部的 icon与文字颜色会被强制设置成白色，感觉这个颜色强行设置有些问题，背景透明不应该涉及到文字颜色。
![image](https://user-images.githubusercontent.com/25143884/98208433-3b846100-1f78-11eb-9dd1-c65a98fa7ad7.png)
![image](https://user-images.githubusercontent.com/25143884/98208781-daa95880-1f78-11eb-96a1-1445511646ef.png)

- 'assist'类型时白色背景色，但是从应用上，是不是应该是透明背景色比较好？如果是这样的话，那assist和ghost的功用上的区分是什么？

**Comment by huskylengcb** [comment]
'assist'类型时白色背景色是错误的，应该是透明背景
ghost中文字icon就应该是白色的

**Comment by WORLDI** [comment]
https://github.com/growingio/gio-design/pull/425

**Comment by LEEHONCN** [comment]
目前只是把 默认辅助按钮默认状态下的样式变透明了，但是其他状态也要注意，比如disabled。还有就是gio-btn 样式不应该有background等属性，而是把这些具体表现放到 具体的className上。
