### ISSUE TITLE
[List]  点击两次同一项 第二次传给 onChange null 

### ISSUE THREAD

**Issue by LEEHONCN** [growingio/gio-design#424]
**Describe the bug**
点击两次同一项 第二次传给 onChange null 

**To Reproduce**
点击两次List的同一项

**Expected behavior**
这是在使用Select的时候发现的问题，对于Select第二次点击应该还是选中（antd 是这样）。最终发现是List 的问题。
我觉得 List 本身应该不用保存任何状态，只需要提供onClick事件返回被点击项的Key。具体如何有待讨论。

**Screenshots**
<img width="653" alt="截屏2020-11-05 下午4 04 59" src="https://user-images.githubusercontent.com/29272287/98213822-9d48c900-1f80-11eb-9eb7-8fc170f5593b.png">

**Comment by phyzess** [comment]
建议 List 本身不应该保存任何状态，除非切换成带有 checkbox 的模式或者从外部控制 value和onChange/onClick/onSelect

**Comment by zzt1224** [comment]
Duplicate of #519
