### ISSUE TITLE
[Input] Input 未对传入的className进行合并，而是直接覆盖了

### ISSUE THREAD

**Issue by phyzess** [growingio/gio-design#436]
Input 没有对外部传入 className 进行合并
且外部样式与类名应用在wrap还是内部input上概念上比较模糊，希望能明确一下

**Comment by LEEHONCN** [comment]
@phyzess 这个问题我在这里解决了，但是影响了Select的样式。 https://github.com/growingio/gio-design/pull/431

**Comment by phyzess** [comment]
> @phyzess 这个问题我在这里解决了，但是影响了Select的样式。 #431

看了下className 覆盖问题是解决了，不过对于外部传入的 className 以及外部的传入的 style 是在 wrapper 上还是 input 上生效的处理有分歧。
类似 border, background 等样式最好放在 wrap 的 div 上，这样也能包裹住 prefix, suffix 等附加组件。input 本身样式上透明，只是占满 wrap中的空白位置

**Comment by LEEHONCN** [comment]
嗯嗯，对。  @jack0pan

**Comment by LEEHONCN** [comment]
> Input 没有对外部传入 className 进行合并
> 且外部样式与类名应用在wrap还是内部input上概念上比较模糊，希望能明确一下

**Comment by LEEHONCN** [comment]
> > @phyzess 这个问题我在这里解决了，但是影响了Select的样式。 #431
> 
> 看了下className 覆盖问题是解决了，不过对于外部传入的 className 以及外部的传入的 style 是在 wrapper 上还是 input 上生效的处理有分歧。
> 类似 border, background 等样式最好放在 wrap 的 div 上，这样也能包裹住 prefix, suffix 等附加组件。input 本身样式上透明，只是占满 wrap中的空白位置

大改样式，也会影响其他组件。建议一鼓作气的修改。
