### ISSUE TITLE
[Select] 需要定义交互逻辑

### ISSUE THREAD

**Issue by LEEHONCN** [growingio/gio-design#447]
**Describe the bug**
现在的逻辑：
在单选模式：
1. 现在对于 disabled 或 可选择 的选项， 点击后是关闭下拉框的。
2. 点击 active 的项，会取消选中，并关闭下拉框

在多选模式： 
1. 点击 disabled 的选项 会关闭下拉框。
2. 点击 可选择的选项 则继续选择不会关闭下拉框。
3. 点击 active 的项，会取消选中，不会关闭下拉框。

对此我有两个疑问
<s>1. 点击 disabled 是否应该关闭下拉框。</s>
2. 在单选模式点击 active的项 是否应该取消选中。

此外 List 组件的状态逻辑与Select 相似，那么 List 的交互逻辑应该是怎么样？

**Comment by LEEHONCN** [comment]
点击 disabled 的选项会关闭下拉框的问题通过改Dropdown已经解决了

**Comment by zzt1224** [comment]
2. 在单选模式点击 active的项 是否应该取消选中。
list决定这个地方的逻辑

**Comment by zzt1224** [comment]
Duplicate of #519
