### ISSUE TITLE
[Modal] 如果不传入 destroyOnClose 那么close 后蒙层依然存在

### ISSUE THREAD

**Issue by LEEHONCN** [growingio/gio-design#459]
**Describe the bug**
如果不传入 destroyOnClose 那么close 后蒙层依然存在。
表现并不像demo所示会有一个 gio-modal-mask-hidden 样式

**Screenshots**
![截屏2020-11-11 下午1 43 44](https://user-images.githubusercontent.com/29272287/98773619-43cf1700-2424-11eb-9779-396d2e127e32.png)

**Additional context**

**Comment by LEEHONCN** [comment]
发现是去掉antd 样式引起的问题，我们的组件直接或间接使用的rc-animate 就可能导致这个问题

**Comment by LEEHONCN** [comment]
引入antd的动画样式即可解决问题

**Comment by huskylengcb** [comment]
-
