### ISSUE TITLE
[Menu] 去掉ul 的默认margin-top

### ISSUE THREAD

**Issue by LEEHONCN** [growingio/gio-design#460]
**Describe the bug**
Menu 现在有一个ul的默认样式, margin-top: 1em。 在demo中，被umi的样式给覆盖了，因此没有问题。
在去掉antd样式的项目中这个问题会暴露出来。

**Additional context**
其他组件也应该会有一些默认样式的问题，我们在demo环境开发的时候被忽略了。我们是把这种问题在组件上解决还是依赖一个 统一的处理样式文件。

**Comment by phyzess** [comment]
@LEEHONCN 等storybook 的 demo 环境弄好之后，在那个基础上统一改一下样式吧到时候
