### ISSUE TITLE
[Storybook] 组件在storybook上的样式问题

### ISSUE THREAD

**Issue by huqiyao** [growingio/gio-design#476]
- [x] Input组件没有box-sizing: border-box，造成高度宽度异常（对多个组件都有影响） @HunterGitHub 
- [ ] Menu组件SubMenu下的MenuItem没有显示 @phyzess 
- [ ] Drawer组件transform: translateX偏移量不对，导致关闭后有部分范围依然可见
- [x] Select组件没有box-sizing: border-box，造成宽高度异常 @zzt1224 
- [ ] Form组件FormItem中加入Icon后宽度变大，导致和没有加Icon的FormItem宽度不一致 @iahu

**Comment by jack0pan** [comment]
@HunterGitHub @phyzess @zzt1224 @iahu 几位抽空看一下这些问题
