### ISSUE TITLE
[input] onchange描述与实际不符

### ISSUE THREAD

**Issue by berber1016** [growingio/gio-design#527]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by berber1016** [comment]
onChange | 修改值时触发的回调函数 | Function(value: string) | 必填
这是文档里的描述 但是在代码中 onchange的参数是 React.ChangeEvent<HTMLInputElement>

**Comment by WORLDI** [comment]
使用没问题的话是不是改一下文档就好了

**Comment by HunterGitHub** [comment]
这个问题在 bf59a0e91ac34a3472b6bfd89c46573205822f04 这个commit 里被覆盖回去了，导致信息错误，我把它还原回来
