### ISSUE TITLE
[Menu] menu组件也太~不健壮了，menu下面只能是submenu或者menuitem吗？废话不多说，上图

### ISSUE THREAD

**Issue by huskylengcb** [growingio/gio-design#528]
![屏幕快照 2020-11-25 16 52 37](https://user-images.githubusercontent.com/28557953/100204515-e916de80-2f3e-11eb-86fd-1930d4eeb6ea.png)

这种给支持一下吧

**Comment by phyzess** [comment]
啥场景需要这个啊
