### ISSUE TITLE
[Menu] menuItem 距离左端padding不能写死44px !importent。demo中只考虑submenu有icon的情况，没考虑没有icon的情况

### ISSUE THREAD

**Issue by huskylengcb** [growingio/gio-design#529]
![屏幕快照 2020-11-25 17 00 41](https://user-images.githubusercontent.com/28557953/100205523-334c8f80-2f40-11eb-85dc-f10d28113e0a.png)
![屏幕快照 2020-11-25 17 00 54](https://user-images.githubusercontent.com/28557953/100205529-347dbc80-2f40-11eb-9a59-5d2484cb5fbd.png)
<img width="281" alt="屏幕快照 2020-11-25 17 01 29" src="https://user-images.githubusercontent.com/28557953/100205533-35aee980-2f40-11eb-95f5-8a2b34b04b8f.png">

**Comment by phyzess** [comment]
。。。这个是当时设计师说 SubMenu 绝对不能有 Icon

**Comment by phyzess** [comment]
哦我表述错了。。。
