### ISSUE TITLE
[All components] 全局样式处理

### ISSUE THREAD

**Issue by LEEHONCN** [growingio/gio-design#530]
**Describe the bug**
在我们的项目中，会有直接或间接引入的 normalize.css 样式。在dumi 中也会全局样式影响我们写出来的样式。
这两种因素都会影响组件的表现。

**Additional context**
我们组件是否需要引入 normalize.css 样式？

类似的问题 https://github.com/growingio/gio-design/issues/460

**Comment by jack0pan** [comment]
这种问题不应该是组件库来解决。

**Comment by LEEHONCN** [comment]
antd 使用了 normalize.css 样式，如果我们不使用，则需要确定所有使用组件的项目没有它。

**Comment by jack0pan** [comment]
嗯，我们慢慢的从所有项目里移除它。

**Comment by phyzess** [comment]
组件库里面的话，最好是进行收敛在组件库里进行自己的作用域里面的normalize，不要把这个东西扩散到全局作用域里面。不然那效果就跟 antd 用的normalize.css一样恶心了
