### ISSUE TITLE
[Select] 当自定义搜索使用pinyinFilter时，defaultLabelRenderer 渲染与预期不符

### ISSUE THREAD

**Issue by LEEHONCN** [growingio/gio-design#548]
**Describe the bug**
当自定义搜索使用pinyinFilter时，defaultLabelRenderer 使用 indexOf 会导致渲染错误

**Expected behavior**
不会出现截取错误。

**Screenshots**
![截屏2020-11-27 下午6 41 28](https://user-images.githubusercontent.com/29272287/100440666-32eafa80-30e0-11eb-8511-47c0896f0e48.png)
![截屏2020-11-27 下午6 41 31](https://user-images.githubusercontent.com/29272287/100440653-3088a080-30e0-11eb-8839-ef435926bc94.png)

**Comment by berber1016** [comment]
如果可以的话自定义LabelRender，defaultLabelRenderer只是针对输入的情况返回了匹配的结果，利用pinyin-match返回位置然后自定义labelRender即可达成截取高亮
