### ISSUE TITLE
[Select] 需要 clear 功能来清除选中的内容

### ISSUE THREAD

**Issue by LEEHONCN** [growingio/gio-design#604]
类似于下图的功能
<img width="163" alt="截屏2020-12-10 下午3 01 17" src="https://user-images.githubusercontent.com/29272287/101732684-915ca380-3af8-11eb-8e70-41493328ec39.png">

**Comment by berber1016** [comment]
https://ant.design/components/select-cn/    需要 allowClear 来开启清除功能，任何模式下都可以开启清除模式，非https://github.com/growingio/gio-design/issues/448中描述的在单选且搜索模式的时候， 当前已修正版本issues描述的想要清空内容时需要一直按backspace
