### ISSUE TITLE
[Menu] mode = 'vertical'   Menu.js:51 Uncaught TypeError: Cannot read property 'type' of null

### ISSUE THREAD

**Issue by LEEHONCN** [growingio/gio-design#614]
当 mode = 'vertical' 时， 且 Menu下直接使用MenuItem。
**Screenshots**
<img width="621" alt="截屏2020-12-14 下午8 29 14" src="https://user-images.githubusercontent.com/29272287/102081341-09a1cc80-3e4b-11eb-8d0f-e5c82a253fcc.png">

**Comment by phyzess** [comment]
我刚才在我这里也复现了一下，发现应该是在 Menu 下面传入了比如说undefined这样的东西导致的，做一下空值的排除
