### ISSUE TITLE
[Modal] 支持自定义高度

### ISSUE THREAD

**Issue by LEEHONCN** [growingio/gio-design#639]
**Is your feature request related to a problem? Please describe.**
当前有个设计稿AC是要求弹窗最大高度为640px，现在尝试过使用 bodyStyle 并不能实现。 个人感觉这种要求弹窗高度的设计还是蛮常见的。

![image](https://user-images.githubusercontent.com/29272287/102844910-6272f580-4447-11eb-8db1-d8c2306ca23a.png)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jack0pan** [comment]
![image](https://user-images.githubusercontent.com/3879776/102857165-e5ee1000-4462-11eb-9545-f33a463bff51.png)

Modal 组件这不是实现了吗？
