### ISSUE TITLE
[TreeSelect] 输入时两个图标同时存在

### ISSUE THREAD

**Issue by WORLDI** [growingio/gio-design#688]
**Describe the bug**
![image](https://user-images.githubusercontent.com/66404428/103621003-7baf9200-4f6f-11eb-9d13-8a6690fe0614.png)

**Comment by huskylengcb** [comment]
![image](https://user-images.githubusercontent.com/28557953/113685738-219ea400-96f9-11eb-9701-f788f56fb1b7.png)

检查自己的项目看看是不是哪里动了样式了，从growingio.design以及企业服务使用情况，并没有发现这个问题
