### ISSUE TITLE
[CheckboxGroup] style文件未加载

### ISSUE THREAD

**Issue by huqiyao** [growingio/gio-design#723]
![gif](https://s31.aconvert.com/convert/p3r68-cdx67/yj5ck-8t67b.gif)

刷新后，CheckboxGroup组件的index.less未加载，导致样式很奇怪：
![image](https://user-images.githubusercontent.com/38038523/104870242-fa9ac680-5982-11eb-93e4-503406e2575e.png)

手动@import '@gio-design/components/es/components/checkbox/style/index.less';后才会正常

**Comment by zzt1224** [comment]
webpack配置自动引入样式
