### ISSUE TITLE
[Input] 浏览器密码自动填充造成的样式问题

### ISSUE THREAD

**Issue by LEEHONCN** [growingio/gio-design#732]
**Describe the bug**
浏览器自动填充 input 元素造成的样式问题

**Screenshots**
<img width="621" alt="截屏2021-01-21 下午1 53 03" src="https://user-images.githubusercontent.com/29272287/105285753-fc1cf680-5bef-11eb-9281-8eae902d3d1b.png">

**Additional context**
建议使 input元素 与 Input 组件完全重合

**Comment by itiiss** [comment]
chrome浏览器的Input自动填充基础样式，可以给input:-internal-autofill-selected 这个类加一个超长的动画解决

**Comment by LEEHONCN** [comment]
> chrome浏览器的Input自动填充基础样式，可以给input:-internal-autofill-selected 这个类加一个超长的动画解决

这里说的是input元素 与 Input 组件没有完全重合，导致 suffix 部分没有自动填充的样式。

**Comment by berber1016** [comment]
已复现该问题，预计下个版本修复
