### ISSUE TITLE
[ToolTip] destroyTooltipOnHide属性

### ISSUE THREAD

**Issue by zzt1224** [growingio/gio-design#739]
DestroyTooltipOnHide 为 True的时候 Tooltip隐藏仍有dom残留
![Screen Shot 2021-01-25 at 10 59 39 AM](https://user-images.githubusercontent.com/12127836/105656150-8b7e1e80-5efc-11eb-9d25-aa4d699e5e36.png)

**Comment by LEEHONCN** [comment]
依赖的组件就存在这个问题

**Comment by zzt1224** [comment]
Dependency issue
