### ISSUE TITLE
[Tree] Tree 组件上添加 ” 点击 TreeNode “ 展开树节点的功能

### ISSUE THREAD

**Issue by ma-xin-developer** [growingio/gio-design#822]
有一个需求，是 【点击 TreeNode 也能像点击小三角一样实现展开或收起】的功能，目前 Tree 组件没有提供这个功能。

1. 请问有必要新加这个功能吗？
2. 如果新加这个功能会不会对其他功能产生影响？

**Comment by huskylengcb** [comment]
这个不应该加，因为点击TreeNode是另一个事件，比如“选中”
